version: '3.4'

services:
  inventoryservices:
    image: ${DOCKER_REGISTRY-}inventoryservices
    build:
      context: .
      dockerfile: InventoryServices/Dockerfile

  productservices:
    image: ${DOCKER_REGISTRY-}productservices
    build:
      context: .
      dockerfile: ProductServices/Dockerfile

